Bash
acliu/21cmStarterKit pull request #2
Opened 2019-12-30 23:31 UTC by joellebegin

making some documents to introduce people to bash scripts

2019-12-30 23:41 UTC, acliu requested changes
Another thing: I assume you meant to call the folder `bash_scripts` rather than `bash_scrips`?

2019-12-30 23:41 UTC, acliu commented on bash_scrips/intro_to_bash.md
> +
I think we should add the author's name and the date below each of our little tutorials.

2019-12-30 23:41 UTC, acliu commented on bash_scrips/distributions.py
> +    main()
Convention is to have a new line at the end of files.

2019-12-30 23:41 UTC, acliu commented on bash_scrips/histograms.py
> +    main()
Convention is to have a new line at the end of files.

2020-06-21 18:44 UTC, joellebegin commented
Hi Adrian I satisfied all the change requests (this is long overdue, I know) but I don't know how to tell github that it's fixed :( I don't know if you have to review again before merging.

2020-06-21 18:57 UTC, acliu approved these changes

2020-06-23 22:32 UTC, merged